### ISSUE TITLE
Fix NetSoC on Digilent Atlys board

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/opsis-soc#43]
```
Phase 3.31  Local Placement Optimization (Checksum:e349d6cb) REAL time: 19 secs 

Phase 4.2  Initial Placement for Architecture Specific Features

................
ERROR:Place:1108 - A clock IOB / BUFGMUX clock component pair have been found
   that are not placed at an optimal clock IOB / BUFGMUX site pair. The clock
   IOB component <eth_clocks_rx> is placed at site <K15>. The corresponding BUFG
   component <BUFGMUX> is placed at site <BUFGMUX_X3Y6>. There is only a select
   set of IOBs that can use the fast path to the Clocker buffer, and they are
   not being used. You may want to analyze why this problem exists and correct
   it. If this sub optimal condition is acceptable for this design, you may use
   the CLOCK_DEDICATED_ROUTE constraint in the .ucf file to demote this message
   to a WARNING and allow your design to continue. However, the use of this
   override is highly discouraged as it may lead to very poor timing results. It
   is recommended that this error condition be corrected in the design. A list
   of all the COMP.PINs used in this clock placement rule is listed below. These
   examples can be used directly in the .ucf file to override this clock rule.
   < NET "eth_clocks_rx" CLOCK_DEDICATED_ROUTE = FALSE; >

Phase 4.2  Initial Placement for Architecture Specific Features
(Checksum:e19ba922) REAL time: 40 secs 

Total REAL time to Placer completion: 40 secs 
Total CPU  time to Placer completion: 39 secs 
ERROR:Pack:1654 - The timing-driven placement phase encountered an error.

Mapping completed.
See MAP report file "top_map.mrp" for details.
Problem encountered during the packing phase.

Design Summary
--------------
Number of errors   :   2
Number of warnings :   4
Traceback (most recent call last):
  File "./make.py", line 72, in <module>
    main()
  File "./make.py", line 65, in main
    vns = builder.build(**dict(args.build_option))
  File "/home/tansell/foss/timvideos/lite/opsis-soc/third_party/litex/litex/soc/integration/builder.py", line 161, in build
    **kwargs)
  File "/home/tansell/foss/timvideos/lite/opsis-soc/third_party/litex/litex/soc/integration/soc_core.py", line 208, in build
    return self.platform.build(self, *args, **kwargs)
  File "/home/tansell/foss/timvideos/lite/opsis-soc/third_party/litex/litex/build/xilinx/platform.py", line 29, in build
    return self.toolchain.build(self, *args, **kwargs)
  File "/home/tansell/foss/timvideos/lite/opsis-soc/third_party/litex/litex/build/xilinx/ise.py", line 176, in build
    self.map_opt, self.par_opt)
  File "/home/tansell/foss/timvideos/lite/opsis-soc/third_party/litex/litex/build/xilinx/ise.py", line 120, in _run_ise
    raise OSError("Subprocess failed")
OSError: Subprocess failed
make: *** [gateware] Error 1
```

**Comment by mithro** [comment]
The old misoc firmware does;
```
        platform.add_platform_command("""
# Separate TMNs for FROM:TO TIG constraints
NET "{eth_clocks_rx}" CLOCK_DEDICATED_ROUTE = FALSE;
```

**Comment by mithro** [comment]
Temporary fix in https://github.com/mithro/HDMI2USB-litex-firmware/commit/89aa5068c0dd23acd0ecba8969ff5f218070e7f5

**Comment by mithro** [comment]
@enjoy-digital - What is the status of this?

**Comment by mithro** [comment]
Related to this, right? https://github.com/enjoy-digital/opsis-soc/issues/45

**Comment by enjoy-digital** [comment]
Closing, now tracked in: https://github.com/timvideos/HDMI2USB-litex-firmware
